config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'welcome#index', as: 'home'
  get 'persons/profile', as: 'user_root'
  devise_for :users
  resources :pizzas
  resources :orders
  resources :urls
  resources :notes
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
# frozen_string_literal: true

class Note < ApplicationRecord
  belongs_to :user
  validates :message, presence: true
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  validates :title, :price, :name, :email, :phone, presence: true
end

app/models/pizza.rb
# frozen_string_literal: true

class Pizza < ApplicationRecord
  validates :title, :description, :price, :size, :path_to_image, presence: true
  validates_inclusion_of :is_spicy, :is_veg, :best_offer, in: [true, false]
end

app/models/url.rb
# frozen_string_literal: true

class Url < ApplicationRecord
  belongs_to :user
  validates :new_url, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  validates :email, :nickname, :password, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :notes, dependent: :destroy
  has_many :urls, dependent: :destroy
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/notes_controller.rb
# frozen_string_literal: true

class NotesController < ApplicationController
  before_action :authenticate_user!,
                only: %i[edit new create update destroy show index]
  def index
    @notes = current_user.notes
  end

  def show
    @note = Note.find(params[:id])
  end

  def new
    @note = Note.new
  end

  def edit
    @note = Note.find(params[:id])
  end

  def create
    @note = current_user.notes.build(note_params)
    if @note.save
      redirect_to @note
    else
      render 'new'
    end
  end

  def update
    @note = Note.find(params[:id])
    if @note.update(note_params)
      redirect_to @note
    else
      render 'edit'
    end
  end

  def destroy
    @note = Note.find(params[:id])
    @note.destroy
    redirect_to notes_path
  end

  private

  def note_params
    params.require(:note).permit(:current_user, :message)
  end
end

app/controllers/orders_controller.rb
# frozen_string_literal: true

class OrdersController < ApplicationController
  before_action :authenticate_user!

  def show
    @order = Order.find(params[:id])
  end

  def new
    @order = Order.new
  end

  def edit
    @order = Order.find(params[:id])
  end

  def create
    @order = Order.new(order_params)
    if @order.save
      redirect_to @order
    else
      render 'new'
    end
  end

  def update
    @order = Order.find(params[:id])
    if @order.update(order_params)
      redirect_to @order
    else
      render 'edit'
    end
  end

  def destroy
    @order = Order.find(params[:id])
    @order.destroy
    redirect_to orders_path
  end

  private

  def order_params
    params.require(:order).permit(:title, :description, :name, :email, :phone)
  end
end

app/controllers/persons_controller.rb
# frozen_string_literal: true

class PersonsController < ApplicationController
  def profile; end
end

app/controllers/pizzas_controller.rb
# frozen_string_literal: true

class PizzasController < ApplicationController
  before_action :authenticate_user!, except: %i[show index]

  def index
    @pizzas = Pizza.all
  end

  def show
    @pizza = Pizza.find(params[:id])
  end

  def new
    @pizza = Pizza.new
  end

  def edit
    @pizza = Pizza.find(params[:id])
  end

  def create
    @pizza = Pizza.new(pizza_params)
    if @pizza.save
      redirect_to @pizza
    else
      render 'new'
    end
  end

  def update
    @pizza = Pizza.find(params[:id])
    if @pizza.update(pizza_params)
      redirect_to @pizza
    else
      render 'edit'
    end
  end

  def destroy
    @pizza = Pizza.find(params[:id])
    @pizza.destroy
    redirect_to pizzas_path
  end

  private

  def pizza_params
    params.require(:pizza).permit(:title,
                                  :description,
                                  :price,
                                  :size,
                                  :is_spicy,
                                  :is_veg,
                                  :best_offer,
                                  :path_to_image)
  end
end

app/controllers/urls_controller.rb
# frozen_string_literal: true

class UrlsController < ApplicationController
  before_action :authenticate_user!,
                only: %i[edit new create update destroy show index]
  def index
    @urls = current_user.urls
    @status = '200'
    end

  def show
    @url = Url.find(params[:id])
  end

  def status; end

  def new
    @url = Url.new
  end

  def edit
    @url = Url.find(params[:id])
  end

  def create
    @url = current_user.urls.build(url_params)
    if @url.save
      redirect_to @url
    else
      render 'new'
    end
  end

  def update
    @url = Url.find(params[:id])
    if @url.update(url_params)
      redirect_to @url
    else
      render 'edit'
    end
  end

  def destroy
    @url = Url.find(params[:id])
    @url.destroy
    redirect_to urls_path
  end

  private

  def url_params
    params.require(:url).permit(:old_url, :new_url)
  end
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/notes_helper.rb
# frozen_string_literal: true

module NotesHelper
end

app/helpers/orders_helper.rb
# frozen_string_literal: true

module OrdersHelper
end

app/helpers/persons_helper.rb
# frozen_string_literal: true

module PersonsHelper
end

app/helpers/pizzas_helper.rb
# frozen_string_literal: true

module PizzasHelper
end

app/helpers/urls_helper.rb
# frozen_string_literal: true

module UrlsHelper
end

app/helpers/welcome_helper.rb
# frozen_string_literal: true

module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>RailsPizza</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.0/css/bootstrap.min.css" integrity="sha384-PDle/QlgIONtM1aqA2Qemk5gPOE7wFq8+Em+G/hmo5Iq0CCmYZLv3fVRDJ4MMwEA" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
  <h5 class="my-0 mr-md-auto font-weight-normal">Portfolio</h5>
  <nav class="my-2 my-md-0 mr-md-3">
    <span class="badge badge-light"><%= link_to 'Main page', home_path %></span>
    <span class="badge badge-light"><%= link_to 'Your profile', user_root_path %></span>
    <span class="badge badge-light"><%= link_to 'Pizza', pizzas_path %></span>
    <span class="badge badge-light"><%= link_to 'Notes', notes_path %></span>
    <span class="badge badge-light"><%= link_to 'Url', urls_path %></span>
  </nav>
  <% if user_signed_in? %>
    <%= link_to "Log out", destroy_user_session_path, :method => :delete, :class => "btn btn-outline-danger btn-sm" %>
  <% else %>
    <%= link_to "Log in", new_user_session_path, :class => "btn btn-outline-success btn-sm" %>
  <% end %>
</div>
  <div class="container">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%=yield%>
    </div>
  </div>
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.0/js/bootstrap.min.js" integrity="sha384-7aThvCh9TypR7fIc2HV4O/nFMVCBwyIUKL8XCtKE+8xgCgl/PQGuFsvShjr74PBp" crossorigin="anonymous"></script>
  </body>

</html>

app/views/notes/_form.html.erb
<%= form_with model: @note, local: true do |form| %>

  <% if @note.errors.any? %>
    <% @note.errors.full_messages.each do |msg| %>
      <div class='alert alert-danger'><%= msg %></div>
    <% end %>
  <% end %>

  <p>
    <% form.label :nickname %><br>
    <% form.text_field(:nickname,{:class => 'form-control'}) %>
  </p>
  <p>
    <%= form.label :message %><br>
    <%= form.text_field(:message,{:class => 'form-control'}) %>
  </p>
  <p>
    <%= form.submit(:class => 'btn btn-outline-primary btn-sm') %>
  </p>
<% end %>

app/views/notes/edit.html.erb
<h2>Notes edit</h2>
<hr>
<%= render 'form' %>
<hr>
<%= link_to "Back", notes_path, :class => "btn btn-outline-primary btn-sm" %>
<%= link_to "Delete note", note_path(@note), method: :delete, :class => "btn btn-outline-primary btn-sm" %>

app/views/notes/index.html.erb
<h2>Notes</h2>
<%= link_to 'Add note', new_note_path(@note), :class => "btn btn-outline-primary btn-sm" %>
<hr>
<div class="row">
  <%@notes.each do |t|%>
    <div class ="col-sm">
      <div>
        <%="nickname: #{t.user.nickname}"%>
      </div>
      <div>
        <%="note: #{t.message}"%>
      </div>
      <td><%= link_to 'Show', note_path(t), :class => "btn btn-outline-primary btn-sm" %></td>
      <hr>
    </div>
  <%end%>
</div>

app/views/notes/new.html.erb
<h2>Write new note</h2>
<hr>
<%= render 'form' %>
<hr>
<%= link_to "Back", notes_path, :class => "btn btn-outline-primary btn-sm" %>

app/views/notes/show.html.erb
<h2>Show note</h2>
<hr>
<p>
  <strong>Nickname:</strong>
  <%= @note.user.nickname %>
</p>
<p>
  <strong>Text:</strong>
  <%= @note.message %>
</p>
<hr>
<%= link_to "Edit", edit_note_path(@note), :class => "btn btn-outline-primary btn-sm" %>
<%= link_to "Back", notes_path, :class => "btn btn-outline-primary btn-sm" %>

app/views/orders/_form.html.erb
<%= form_with model: @order, local: true do |form| %>

  <% if @order.errors.any? %>
    <% @order.errors.full_messages.each do |msg| %>
      <div class='alert alert-danger'><%= msg %></div>
    <% end %>
  <% end %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field(:title, {:class => 'form-control'}) %>
  </p>
  <p>
    <%= form.label :price %><br>
    <%= form.text_field(:price, {:class => 'form-control'}) %>
  </p>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field(:name, {:class => 'form-control'}) %>
  </p>
  <p>
    <%= form.label :email %><br>
    <%= form.text_field(:email, {:class => 'form-control'}) %>
  </p>
  <p>
    <%= form.label :phone %><br>
    <%= form.text_field(:phone, {:class => 'form-control'}) %>
  </p>
  <p>
    <%= form.submit(:class => 'btn btn-outline-primary btn-sm') %>
  </p>
<% end %>

app/views/orders/edit.html.erb
<h2>Orders edit</h2>
<hr>
<%= render 'form' %>
<hr>
<%= link_to "Back", orders_path, :class => "btn btn-outline-primary btn-sm" %>
<%= link_to "Destroy", order_path(@order), method: :delete, :class => "btn btn-outline-primary btn-sm" %>

app/views/orders/new.html.erb
<h2>New order</h2>
<hr>
<%= render 'form' %>
<hr>
<%= link_to "Back", orders_path, :class => "btn btn-outline-primary btn-sm" %>

app/views/orders/show.html.erb
<h2>Show order</h2>
<p>
  <strong>Title:</strong>
  <%= @order.title %>
</p>
<p>
  <strong>Price:</strong>
  <%= @order.price %>
</p>
<p>
  <strong>Name:</strong>
  <%= @order.name %>
</p>
<p>
  <strong>Email:</strong>
  <%= @order.email %>
</p>
<p>
  <strong>Phone:</strong>
  <%= @order.phone %>
</p>
<%= link_to "Edit", edit_order_path(@order), :class => "btn btn-outline-primary btn-sm" %>
<%= link_to "Back", orders_path, :class => "btn btn-outline-primary btn-sm" %>

app/views/persons/profile.html.erb
<h2>Your profile</h2>
<% if user_signed_in? %>
  <span>Hello, <%= current_user.nickname %></span>
  <span class="btn btn-outline-danger btn-sm"><%= link_to 'Log out', destroy_user_session_path, :method => :delete %></span>
<% else %>
  <span class="btn btn-outline-success btn-sm"><%= link_to 'Log in', new_user_session_path %></span> or <span class="btn btn-outline-success btn-sm"><%= link_to 'Sign up', new_user_registration_path %></span>
<% end %>
<hr>

app/views/pizzas/_form.html.erb
<%= form_with model: @pizza, local: true  do |form| %>

  <% if @pizza.errors.any? %>
    <% @pizza.errors.full_messages.each do |msg| %>
      <div class='alert alert-danger'><%= msg %></div>
    <% end %>
  <% end %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field(:title, {:class => 'form-control'}) %>
  </p>
  <p>
    <%= form.label :description %><br>
    <%= form.text_field(:description, {:class => 'form-control'}) %>
  </p>
  <p>
    <%= form.label :price %><br>
    <%= form.text_field(:price, {:class => 'form-control'}) %>
  </p>
  <p>
    <%= form.label :size %><br>
    <%= form.text_field(:size, {:class => 'form-control'}) %>
  <p>
    <%= form.label :is_spicy %><br>
    <%= form.text_field(:is_spicy, {:class => 'form-control'}) %>
  </p>
  <p>
    <%= form.label :is_veg %><br>
    <%= form.text_field(:is_veg, {:class => 'form-control'}) %>
  </p>
  <p>
    <%= form.label :best_offer %><br>
    <%= form.text_field(:best_offer, {:class => 'form-control'}) %>
  </p>
  <p>
    <%= form.label :path_to_image %><br>
    <%= form.text_field(:path_to_image, {:class => 'form-control'}) %>
  </p>
  <p>
    <%= form.submit(:class => 'btn btn-outline-primary btn-sm') %>
  </p>
<% end %>

app/views/pizzas/edit.html.erb
<h2>Pizzas edit</h2>
<hr>
<%= render 'form' %>
<hr>
<%= link_to "Back", pizzas_path, :class => "btn btn-outline-primary btn-sm" %>
<%= link_to "Destroy", pizza_path(@pizza), method: :delete, :class => "btn btn-outline-primary btn-sm" %>

app/views/pizzas/index.html.erb
<h2>Pizzas</h2>

<%= link_to 'Add or change order', new_order_path(@order), :class => "btn btn-outline-primary btn-sm" %>
<hr>

<div class="row">
  <%@pizzas.each do |t|%>
    <div class ="col-sm">
      <div>
        <%=t.title%>
      </div>
      <div>
        <img src="<%=t.path_to_image%>"/>
      </div>
      <div>
        <%="price: #{t.price} usd"%>
      </div>
      <div>
        <%="size: #{t.size} cm"%>
      </div>
      <div>
        <%="composition: #{t.description}"%>
      </div>
      <div>
        <%="spicy: #{t.is_spicy}"%>
      </div>
      <div>
        <%="veg: #{t.is_veg}"%>
      </div>
      <div>
        <%="best offer: #{t.best_offer}"%>
      </div>
      <hr>
    </div>
  <%end%>
</div>

<%= link_to 'Add or change pizza', new_pizza_path(@pizza), :class => "btn btn-outline-primary btn-sm" %>

app/views/pizzas/new.html.erb
<h2>New pizza</h2>
<hr>
<%= render 'form' %>
<hr>
<%= link_to "Back", pizzas_path, :class => "btn btn-outline-primary btn-sm" %>

app/views/pizzas/show.html.erb
<h2>Show pizza</h2>
<p>
  <strong>Title:</strong>
  <%= @pizza.title %>
</p>
<p>
  <strong>Description:</strong>
  <%= @pizza.description %>
</p>
<p>
  <strong>Price:</strong>
  <%= @pizza.price %>
</p>
<p>
  <strong>Size:</strong>
  <%= @pizza.size %>
</p>
<p>
  <strong>Is spicy?:</strong>
  <%= @pizza.is_spicy %>
</p>
<p>
  <strong>Is veg?:</strong>
  <%= @pizza.is_veg %>
</p>
<p>
  <strong>Best offer:</strong>
  <%= @pizza.best_offer %>
</p>
<p>
  <strong>Path to image:</strong>
  <%= @pizza.path_to_image %>
</p>
<%= link_to "Edit", edit_pizza_path(@pizza), :class => "btn btn-outline-primary btn-sm" %>
<%= link_to "Back", pizzas_path, :class => "btn btn-outline-primary btn-sm" %>

app/views/urls/_form.html.erb
<%= form_with model: @url, local: true do |form| %>

  <% if @url.errors.any? %>
  <% @url.errors.full_messages.each do |msg| %>
    <div class='alert alert-danger'><%= msg %></div>
  <% end %>
<% end %>

  <p>
    <%= form.label :new_url %><br>
    <%= form.text_field(:new_url, {:class => 'form-control'}) %>
  </p>
  <p>
    <%= form.submit(:class => 'btn btn-outline-primary btn-sm') %>
  </p>
<% end %>

app/views/urls/edit.html.erb
<h2>Urls edit</h2>
<hr>
<%= render 'form' %>
<hr>
<%= link_to "Back", urls_path, :class => "btn btn-outline-primary btn-sm" %>
<%= link_to "Destroy", url_path(@url), method: :delete, :class => "btn btn-outline-primary btn-sm" %>

app/views/urls/index.html.erb
<h2>Urls</h2>
<%= link_to 'Add or change url', new_url_path(@url), :class => "btn btn-outline-primary btn-sm" %>
<hr>
<div class="row">
  <%@urls.each do |t|%>
    <div class ="col-sm">
      <div>
        <%=t.new_url%>
      </div>
      <div>
        <%="status: #{@status}"%>
      </div>
      <div>
        <%= link_to 'server status', urls_path, :class => "btn btn-outline-primary btn-sm" %>
      </div>
      <hr>
    </div>
  <%end%>
</div>

app/views/urls/new.html.erb
<h2>New url</h2>
<hr>
<%= render 'form' %>
<hr>
<%= link_to "Back", urls_path, :class => "btn btn-outline-primary btn-sm" %>

app/views/urls/show.html.erb
<h2>Show url</h2>
<p>
  <%= @url.new_url %>
</p>
<%= link_to "Edit", edit_url_path(@url), :class => "btn btn-outline-primary btn-sm" %>
<%= link_to "Back", urls_path, :class => "btn btn-outline-primary btn-sm" %>

app/views/welcome/index.html.erb
<h2>Main page</h2>